### ISSUE TITLE
Toolbar buttons hover color

### ISSUE THREAD

**Issue by louismaximepiton** [Orange-OpenSource/ods-storybook-theme#5]
Hey there,

I was wondering if there was any solution to make the toolbar buttons orange on hover. It seems feasible following this discussion but it might be a bit old: https://github.com/storybookjs/storybook/issues/13578#issuecomment-842797550.

I don't know if there's any documentation about all the options that can be themed, if yes, I could maybe check the list to see if there's more to change here.

**Comment by julien-deramond** [comment]
Thanks for opening this issue @louismaximepiton 
I tried something upstream a few months back via https://github.com/storybookjs/storybook/pull/20169, which was approved but not merged.
Except if I missed something since that PR, there were no options to do it.
